[workspace]
members = [
  "bin/shm-pbx-server",
  "lib/shm-pbx",
  "examples/client-wasi",
  "examples/fizz-buzz",
  "examples/io-uring-semantics",
  "xtask/cbindgen",
]
resolver = "2"

[workspace.dependencies]
shm-pbx = { path = "lib/shm-pbx", version = "0.0.0" }
