[package]
name = "shm-ring"
version = "0.1.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2018"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
shared_memory = "0.11"

[target.'cfg(target_os = "linux")'.dependencies]
linux-futex = "0.1.1"
