[package]
name = "shm-ring"
version = "0.1.0"
authors = ["Andreas Molzer <andreas.molzer@gmx.de>"]
edition = "2018"
license = "Apache-2.0 OR Unlicense OR WTFPL"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
libc = "0.2.76"
shared_memory = "0.11"

[target.'cfg(target_os = "linux")'.dependencies]
linux-futex = "0.1.1"

[dev-dependencies]
assert_fs = "1"
escargot = "0.5"
tempfile = "3"
